notes/urls.py
from django.urls import path
from . import views

app_name = "notes"
urlpatterns = [
    path("", views.home, name="home"),
    path("login_page/", views.login_page, name="login_page"),
    path("login_user/", views.login_user, name="login_user"),
    path("register_page/", views.register_page, name="register_page"),
    path("register_user/", views.register_user, name="register_user"),
    path("logout_user/", views.logout_user, name="logout_user"),
    path("notes/", views.notes, name="notes"),
    path("create_note/", views.create_note, name="create_note"),
    path("delete_note/<int:note_id>/", views.delete_note, name="delete_note"),
]

notesite/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("notes.urls", namespace="notes")),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls()

notes/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError("The Email field must be set")
        if not username:
            raise ValueError("The Username field must be set")

        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username


class Note(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Note by {self.user.username}: {self.text[:20] or 'Empty Note'}"

notes/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Note
from .models import User


def requires_auth(view_func):
    def wrapper(request, *args, **kwargs):
        auth_token = request.COOKIES.get("auth_token")
        if not auth_token:
            return redirect("/login_page/")
        return view_func(request, *args, **kwargs)

    return wrapper


def home(request):
    auth_token = request.COOKIES.get("auth_token")
    if auth_token:
        return redirect("/notes/")
    else:
        return render(request, "notes/home.html")


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            response = redirect(reverse("notes:home"))
            response.set_cookie("auth_token", user.password, httponly=True, secure=True)
            return response
        else:
            return render(
                request, "notes/login_page.html", {"error": "Invalid credentials"}
            )

    return render(request, "notes/login_page.html")


def register_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")

        if not username or not email or not password:
            return render(
                request,
                "notes/register_page.html",
                {"error": "All fields are required"},
            )

        if User.objects.filter(username=username).exists():
            return render(
                request,
                "notes/register_page.html",
                {"error": "Username already exists"},
            )

        if User.objects.filter(email=email).exists():
            return render(
                request, "notes/register_page.html", {"error": "Email already exists"}
            )

        User.objects.create_user(username, email, password)
        return redirect("/login_page/")
    return render(request, "notes/register_page.html")


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("notes:home"))
    response.delete_cookie("auth_token")
    return response


@requires_auth
def notes(request):
    notes = Note.objects.all().order_by("-created_at")
    return render(request, "notes/notes.html", {"notes": notes})


def login_page(request):
    return render(request, "notes/login_page.html")


def register_page(request):
    return render(request, "notes/register_page.html")


@requires_auth
def create_note(request):
    if request.method == "POST":
        text = request.POST.get("text")

        if not text:
            return JsonResponse({"error": "Note text is required"}, status=400)

        Note.objects.create(text=text, user=request.user)
        return HttpResponseRedirect(reverse("notes:notes"))
    return JsonResponse({"error": "Invalid request method"}, status=405)


@requires_auth
def delete_note(request, note_id):
    if request.method == "POST":
        try:
            note = Note.objects.get(id=note_id)
            if note.user == request.user:
                note.delete()
                return HttpResponseRedirect(reverse("notes:notes"))
            else:
                return JsonResponse(
                    {"error": "You do not have permission to delete this note"},
                    status=403,
                )
        except Note.DoesNotExist:
            return JsonResponse({"error": "Note not found"}, status=404)
    return JsonResponse({"error": "Invalid request method"}, status=405)

notes/templates/notes/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'notes/style.css' %}">

<h3>Welcome to the notes app</h3>
<nav>
  <a class="link" href="/login_page/">Log in</a>
  <a class="link" href="/register_page/">Register</a>
</nav>

notes/templates/notes/login_page.html
{% load static %}
<link rel="stylesheet" href="{% static 'notes/style.css' %}">

<form class="log-reg-form" action="{% url 'notes:login_user' %}" method="post">
  <label>
    Username:
    <input type="text" id="username" name="username" />
  </label>
  <label>
    Password:
    <input type="password" id="password" name="password" />
  </label>
  <button class="log-reg-button" type="submit">Log in</button>
  <a class="link" href="/register_page/">Not registered</a>
</form>

notes/templates/notes/notes.html
{% load static %}
<link rel="stylesheet" href="{% static 'notes/style.css' %}">

<header>
  <h2>Notes</h2>
  <form id="logout" action="{% url 'notes:logout_user' %}"><button type="submit">Log out</button></form>
</header>
<main>
  <h4 class="new-note">Create new note</h4>
  <form id="note-form" class="new-note" action="{% url 'notes:create_note' %}" method="post">
    <textarea type="text" name="text" id="text"></textarea>
    <button class="log-reg-button" type="subit">Add</button>
  </form>
  <ul id="notes">
    <h4>Your notes:</h4>
    {% for note in notes %}
    <li id="{{ note.id }}">
      <div>
        <p class="note-date">{{ note.created_at }}</p>
        <p>{{ note.text }}</p>
      </div>
      <form class="delete-note-button" action="{% url 'notes:delete_note' note.id %}" method="post">
        <button type="submit">Delete</button>
      </form>
    </li>
    {% endfor %}
  </ul>
</main>

notes/templates/notes/register_page.html
{% load static %}
<link rel="stylesheet" href="{% static 'notes/style.css' %}">

<form class="log-reg-form" action="{% url 'notes:register_user' %}" method="post">
  <label>
    Username:
    <input type="text" id="username" name="username" />
  </label>
  <label>
    Email:
    <input type="email" id="email" name="email" />
  </label>
  <label>
    Password:
    <input type="password" id="password" name="password" />
  </label>
  <button class="log-reg-button" type="submit">Register</button>
  <a class="link" href="/login_page/">Already registered</a>
</form>